root = "."
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/app/main.go"
  delay = 1000
  exclude_dir = ["tmp", "assets", "vendor", "bin", "build", "deploy"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  full_bin = "APP_ENV=dev APP_USER=air GIN_MODE=release ./tmp/main"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "env", "yaml"]
  kill_delay = 500
  log = "air.log"
  send_interrupt = false
  stop_on_error = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[log]
  time = false

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
