services:
  nginx:
    container_name: nginx
    image: nginx:1.27.1-alpine
    volumes:
      - "./gateway/nginx.conf:/etc/nginx/nginx.conf"
      - ./gateway/logs:/var/log/nginx
    ports:
      - "80:80"
    network_mode: host

networks:
  dev-net:
    external: true
